//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Disabilities_child
    {
        public int code { get; set; }
        public Nullable<int> idKindChild { get; set; }
        public Nullable<int> userCode { get; set; }
        public Nullable<int> dergi { get; set; }
    
        public virtual kindChildren kindChildren { get; set; }
        public virtual users users { get; set; }
    }
}
