//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class @event
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public @event()
        {
            this.Disabilities_Event = new HashSet<Disabilities_Event>();
        }
    
        public int idEvent { get; set; }
        public Nullable<int> idActivity { get; set; }
        public string TZChild { get; set; }
        public string TzVolunteer { get; set; }
    
        public virtual activities activities { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Disabilities_Event> Disabilities_Event { get; set; }
        public virtual Match Match { get; set; }
    }
}
