//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dal
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ProjectEntities : DbContext
    {
        public ProjectEntities()
            : base("name=ProjectEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<activities> activities { get; set; }
        public virtual DbSet<Disabilities_Event> Disabilities_Event { get; set; }
        public virtual DbSet<@event> @event { get; set; }
        public virtual DbSet<kindChildren> kindChildren { get; set; }
        public virtual DbSet<Match> Match { get; set; }
        public virtual DbSet<Preferences> Preferences { get; set; }
        public virtual DbSet<register> register { get; set; }
        public virtual DbSet<users> users { get; set; }
        public virtual DbSet<Disabilities_child> Disabilities_child { get; set; }
    }
}
