//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Preferences
    {
        public int UserCode { get; set; }
        public int idKindChild { get; set; }
        public int levels { get; set; }
    
        public virtual kindChildren kindChildren { get; set; }
        public virtual users users { get; set; }
    }
}
