//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class register
    {
        public int id { get; set; }
        public Nullable<int> idActivity { get; set; }
        public int userCode { get; set; }
        public string status { get; set; }
    
        public virtual activities activities { get; set; }
        public virtual users users { get; set; }
    }
}
