//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class users
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public users()
        {
            this.register = new HashSet<register>();
            this.Disabilities_child = new HashSet<Disabilities_child>();
        }
    
        public int userCode { get; set; }
        public string Tz { get; set; }
        public string lastName { get; set; }
        public string firstName { get; set; }
        public string city { get; set; }
        public string street { get; set; }
        public string phon { get; set; }
        public string mail { get; set; }
        public string password { get; set; }
        public System.DateTime dateborn { get; set; }
        public string status { get; set; }
        public Nullable<bool> isAviable { get; set; }
    
        public virtual Preferences Preferences { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<register> register { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Disabilities_child> Disabilities_child { get; set; }

        public static users Update(users user)
        {
            throw new NotImplementedException();
        }
    }
}
